config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("products.urls", namespace="products")),
    path("users/", include("users.urls", namespace="users")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .apps import ProductsConfig
from . import views

app_name = ProductsConfig.name

urlpatterns = [
    path("new/", views.ProductCreateView.as_view(), name="product_create"),
    path("", views.ProductListView.as_view(), name="product_list"),
    path("<int:pk>/", views.ProductDetailView.as_view(), name="product_detail"),
    path("update/<int:pk>/", views.ProductUpdateView.as_view(), name="product_update"),
    path("delete/<int:pk>/", views.ProductDeleteView.as_view(), name="product_delete"),
]

users/urls.py
from django.urls import path
from .apps import UsersConfig
from .views import UserCreateView, profile, seller_profile
from django.contrib.auth.views import LoginView, LogoutView

app_name = UsersConfig.name

urlpatterns = [
    path("registration/", UserCreateView.as_view(), name="registration"),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", profile, name="profile"),
    path("seller/<int:pk>/", seller_profile, name="seller"),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    seller = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True, default="1"
    )
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.CharField(max_length=200)
    image = models.ImageField(upload_to="products", blank=True, null=True)

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"

    def __str__(self):
        return self.name

products/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Product(models.Model):
    seller = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        default="1",
        verbose_name="Продавец",
    )
    name = models.CharField(max_length=100, verbose_name="Наименование товара")
    price = models.IntegerField(verbose_name="Цена")
    description = models.CharField(max_length=200, verbose_name="Описание")
    image = models.ImageField(
        upload_to="products", blank=True, null=True, verbose_name="Фото товара"
    )
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата и время добавления"
    )
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Дата и время обновления"
    )

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        ordering = ["-updated_at"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        reverse("products:product_detail", kwargs={"pk": self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    image = models.ImageField(
        upload_to="profiles",
        blank=True,
        null=True,
    )
    contact_number = models.CharField(max_length=35)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = "Профиль"
        verbose_name_plural = "Профили"

products/forms.py
from django.forms import ModelForm
from .models import Product


class CreateProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description", "image"]

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Profile


class NewUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ("user", "image", "contact_number")

products/views.py
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
)
from .models import Product
from .forms import CreateProductForm
from django.urls import reverse_lazy


class ProductCreateView(CreateView):
    model = Product
    form_class = CreateProductForm
    success_url = reverse_lazy("products:product_list")

    def form_valid(self, form):
        form.instance.seller = self.request.user
        return super().form_valid(form)


class ProductListView(ListView):
    model = Product
    paginate_by = 3


class ProductDetailView(DetailView):
    model = Product


class ProductUpdateView(UpdateView):
    model = Product
    form_class = CreateProductForm
    success_url = reverse_lazy("products:product_list")


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("products:product_list")

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from .forms import NewUserForm, ProfileForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Profile
from django.views.generic import CreateView
from django.urls import reverse_lazy


class UserCreateView(CreateView):
    model = User
    form_class = NewUserForm
    template_name = "users/registration.html"
    success_url = reverse_lazy("users:login")


@login_required
def profile(request):
    if request.method == "POST":
        user = request.user
        image = request.FILES.get("upload")
        contact_number = request.POST.get("contact_number")
        item = Profile(user=user, image=image, contact_number=contact_number)
        item.save()
        return redirect("users:profile")

    return render(
        request,
        "users/profile.html",
    )


def seller_profile(request, pk):
    seller = User.objects.get(pk=pk)
    context = {"seller": seller}

    return render(request, "users/seller_profile.html", context)

products/templates/products/product_confirm_delete.html
{% extends 'base.html' %} {% load django_bootstrap5 %}
<!--  -->
{% block title %} Удаление {{object}} {% endblock title %}
<!--  -->
{% block content %}
<div class="container">
  <form method="post" class="form">
    <!--  -->
    {% csrf_token %}
    <!--  -->
    <div class="alert alert-danger" role="alert">
      Вы действительно хотите удалить "{{object}}" ?
    </div>
    <a href="{% url 'products:product_list' %}" class="btn btn-success"
      >Отмена</a
    >
    <button type="submit" class="btn btn-danger">Подтвердить</button>
  </form>
</div>
{% endblock content %}

products/templates/products/product_detail.html
{% extends 'base.html' %}
<!--  -->
{% block title %} {{object}} {% endblock title %}
<!--  -->
{% block content %}
<div class="container">
  <div class="card mb-3">
    <div class="row g-0">
      <div class="col-md-4">
        <img
          src="{{object.image.url}}"
          class="img-fluid rounded-start"
          alt="изображение товара"
        />
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">{{object.name}}</h5>
          <p class="card-text">{{object.description}}</p>

          <p class="card-text">Добавил: {{object.seller}}</p>
          <p class="card-text">
            <small class="text-body-secondary"
              >Добавлено: {{object.created_at}}</small
            >
            <br />
            <small class="text-body-secondary"
              >Обновлено: {{object.updated_at}}</small
            >
          </p>
        </div>
        <div class="card-footer">
                  <div class="btn-group" role="group" aria-label="Basic mixed styles example">
            <a
              href="{% url 'products:product_update' object.pk %}"
              type="button"
              class="btn btn-warning"
              >Редактировать</a
            >
            <a
              href="{% url 'products:product_delete' object.pk %}"
              type="button"
              class="btn btn-danger"
              >Удалить</a>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

products/templates/products/product_form.html
{% extends 'base.html' %}
<!---->
{% load django_bootstrap5 %}
<!---->
{% block title %} {% if object %} Обновление {{object}} {% else %} Добавление
товара {% endif %}

{% endblock title %}
<!--  -->
{% block content %}
<div class="container">
  <form method="post" class="form" enctype="multipart/form-data">
    {% csrf_token %} {% bootstrap_form form %}
    <!--    -->
    <button type="submit" class="btn btn-primary">Опубликовать</button>
  </form>
</div>
{% endblock content %}

products/templates/products/product_list.html
{% extends 'base.html' %}
<!---->
{% block title %} Товары {% endblock title %}
<!--  -->
{% block content %}
<div class="container">






    <nav aria-label="Page navigation example">
        <div>
    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
</div>
  <ul class="pagination">
                  {% if page_obj.has_previous %}

    <li class="page-item"><a class="page-link" href="?page=1">В начало</a></li>
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% endif %}

                  {% if page_obj.has_next %}

    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">В конец</a></li>
            {% endif %}

  </ul>
</nav>

      <form method="get" class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Поиск по товарам" aria-label="Search"/>
        <button class="btn btn-outline-success" type="submit">Искать</button>
      </form>

  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for product in object_list %}

    <div class="col">
      <div class="card">
        {% if product.image %}
        <a
          href="{% url 'products:product_detail' product.pk %}"
          style="text-decoration: none; color: black"
        >
          <img
            src="{{product.image.url}}"
            class="card-img-top img-fluid"
            style="height: 200px; object-fit: contain;"
            alt="изображение товара"
          />
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text">{{product.description}}</p>
          </div>
        </a>
        <div class="card-footer">
          <p class="card-text">Добавлено: {{ product.created_at }}</p>

          <div
            class="btn-group"
            role="group"
            aria-label="Basic mixed styles example"
          >
            <a
              href="{% url 'products:product_detail' product.pk %}"
              type="button"
              class="btn btn-success"
              >Подробнее</a
            >
            <a
              href="{% url 'products:product_update' product.pk %}"
              type="button"
              class="btn btn-warning"
              >Редактировать</a
            >
            <a
              href="{% url 'products:product_delete' product.pk %}"
              type="button"
              class="btn btn-danger"
              >Удалить</a
            >
          </div>
        </div>
      </div>
    </div>

    {% endfor %}
  </div>



</div>
{% endblock content %}

templates/base.html
<!-- https://django-bootstrap-v5.readthedocs.io/en/latest/quickstart.html -->
<!--  -->
{% load django_bootstrap5 %}
<!--  -->
{% bootstrap_css %}
<!--  -->
{% bootstrap_javascript %}
<!--  -->
{% bootstrap_messages %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} Без названия {% endblock title %}</title>
  </head>
  <body>
    {% include 'includes/headers.html' %}
    <!--  -->
    {% block content %} Блок контента {% endblock content %}
    <!--  -->
    <div class="container">{% include 'includes/footer.html' %}</div>
  </body>
</html>

templates/includes/footer.html
<footer class="mt-5 pt-4 my-md-5 pt-md-5 border-top">
  <div class="row">
    <div class="col-12 col-md">
      <small class="d-block mb-3 text-body-secondary">&copy; 2017–2025</small>
    </div>
    <div class="col-6 col-md">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="#">Cool stuff</a>
        </li>
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="#"
            >Random feature</a
          >
        </li>
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="#"
            >Team feature</a
          >
        </li>
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="#"
            >Stuff for developers</a
          >
        </li>
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="#"
            >Another one</a
          >
        </li>
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="#">Last time</a>
        </li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="#">Resource</a>
        </li>
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="#"
            >Resource name</a
          >
        </li>
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="#"
            >Another resource</a
          >
        </li>
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="#"
            >Final resource</a
          >
        </li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>About</h5>
      <ul class="list-unstyled text-small">
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="#">Team</a>
        </li>
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="#">Locations</a>
        </li>
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="#">Privacy</a>
        </li>
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="#">Terms</a>
        </li>
      </ul>
    </div>
  </div>
</footer>

templates/includes/headers.html
<div class="container">
  <header
    class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom"
  >
    <div class="col-md-3 mb-2 mb-md-0">
      <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
        <svg
          class="bi"
          width="40"
          height="32"
          role="img"
          aria-label="Bootstrap"
        >
          <use xlink:href="#bootstrap"></use>
        </svg>
      </a>
    </div>
    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
      <li><a href="/" class="nav-link px-2 link-secondary">Главная</a></li>
      <li>
        <a href="{% url 'products:product_create' %}" class="nav-link px-2"
          >Добавить товар</a
        >
      </li>
      <li><a href="#" class="nav-link px-2">...</a></li>
      <li><a href="#" class="nav-link px-2">...</a></li>
      <li><a href="#" class="nav-link px-2">...</a></li>
    </ul>
    <div class="col-md-3 text-end">
      {% if user.is_authenticated %}
      <a type="button" class="btn btn-outline-primary me-2">Профиль</a>
      <form
        style="display: inline"
        action="{% url 'users:logout' %}"
        method="post"
      >
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Выйти</button>
      </form>
      {% else %}
      <a
        href="{% url 'users:login' %}"
        type="button"
        class="btn btn-outline-primary me-2"
        >Войти</a
      >
      <a
        href="{% url 'users:registration' %}"
        type="button"
        class="btn btn-primary"
        >Регистрация</a
      >
      {% endif %}
    </div>
  </header>
</div>

users/templates/users/login.html
{% extends 'base.html' %} {% load django_bootstrap5 %}

<!---->
{% block title %} Вход {% endblock title %}
<!---->
{% block content %}
<div class="container">
  <div class="card">
    <div class="card-header">
      <h3 class="card-title">Вход</h3>
    </div>
    <div class="card-body">
      <form method="POST">
        <!--  -->
        {% csrf_token %} {% bootstrap_form form %}
        <!--  -->
        <button class="btn btn-outline-success" type="submit">Войти</button>
      </form>
    </div>
    <div class="card-footer">
      <p>
        Нет аккаунта? Вы можете
        <a href="{% url 'users:registration' %}">зарегистрироваться</a>.
      </p>
    </div>
  </div>
</div>

{% endblock content %}

users/templates/users/profile.html
{% extends 'myapp/base.html' %}
<!---->
{% block title %} Профиль {% endblock title %}
<!---->
{% block content %}
<h1>Профиль</h1>
{% if user.profile %}
<div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
  <div class="rounded shadow-lg">
    <div>
      {% if user.profile.image %}
      <img
        class="w-[200px]"
        src="{{ user.profile.image.url }}"
        alt="user_avatar"
      />
      {% endif %}
    </div>
    <h1 class="font-bold text-lg">Профиль {{ user.username }}</h1>
    <p>Контактный номер{{ user.profile.contact_number }}</p>
    <!-- <p>Адрес изображения: </p> -->
  </div>
</div>
{% else %}
<div class="container">
  <h1>Создание профиля</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input
      type="file"
      accept="image/"
      placeholder="Фото"
      name="upload"
      id="upload"
    />
    <input
      type="tel"
      placeholder="Контактный телефон"
      name="contact_number"
      id="contact_number"
    />
    <button type="submit">Создать профиль</button>
  </form>
</div>
{% endif %} {% endblock content %}

users/templates/users/registration.html
{% extends 'base.html' %}
<!---->
{% load django_bootstrap5 %}
<!---->
{% block title %} Регистрация {% endblock title %}
<!---->

{% block content %}

<div class="container">
  <div class="card">
    <div class="card-header">
      <h3 class="carв-title">Регистрация</h3>
    </div>
    <div class="card-body">
      <form method="post">
        {% csrf_token %} {% bootstrap_form form %}
        <button type="submit" class="btn btn-outline-success">
          Зарегистрироваться
        </button>
      </form>
    </div>
    <div class="card-footer"></div>
  </div>
</div>

{% endblock %}

users/templates/users/seller_profile.html
{% extends 'myapp/base.html' %}
<!---->
{% block title %} Профиль {% endblock title %}
<!---->
{% block content %}
<h1>Профиль продавца</h1>

<div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
  <div class="rounded shadow-lg">
    <div>
      {% if seller.profile.image %}
      <img
        class="w-[200px]"
        src="{{ seller.profile.image.url }}"
        alt="user_avatar"
      />
      {% endif %}
    </div>
    <h1 class="font-bold text-lg">Профиль {{ seller.username }}</h1>
    <p>Контактный номер{{ seller.profile.contact_number }}</p>
  </div>
</div>
{% endblock content %}